### ISSUE TITLE
namespace "aegis" has no member "create_bot_t"

### ISSUE THREAD

**Issue by sh30801** [zeroxs/aegis.cpp#26]
I just included the include directory in my project settings, however I get this error along with not recognizing "spdlog" as a namespace. Any help would be appreciated.

**Comment by zeroxs** [comment]
[aegis::create_bot_t](https://github.com/zeroxs/aegis.cpp/blob/master/include/aegis/core.hpp#L100)
spdlog requires including the paths to the dependencies. If using Windows, you will need to configure this yourself most likely. If using Linux and CMake, this should be done for you.

**Comment by sh30801** [comment]
I'm not quite sure how to link dependencies in an external library, I'm using Visual Studio 2019. Do you happen to know of any resources to help me do this?

**Comment by NickPryorMe** [comment]
> 
> 
> I'm not quite sure how to link dependencies in an external library, I'm using Visual Studio 2019. Do you happen to know of any resources to help me do this?

https://stackoverflow.com/questions/4445418/how-to-add-additional-libraries-to-visual-studio-project
I also suggest vcpkg for installing any libraries for C++ on Windows.

**Comment by zeroxs** [comment]
If you need a base to start with for Visual Studio, I made a template project that will get you going. https://github.com/zeroxs/aegis.cpp-template

**Comment by sh30801** [comment]
I'll take a look at that then, appreciate the help.
