### ISSUE TITLE
nlohmann/json_fwd.hpp: No such file or directory

### ISSUE THREAD

**Issue by Jm56Z** [zeroxs/aegis.cpp#38]
I cloned the repository with its dependencies, and built the lib:
```
git clone --recursive git@github.com:zeroxs/aegis.cpp
cd aegis.cpp
mkdir build
cd build
cmake ..
make
sudo make install
```
No error until here.

Then I created a little project, with a single `main.cpp` file, containing the template code given in the Readme - in which I took care to replace "TOKEN" with my bot's token, obviously.

When compiling it with
```
g++ -o bot src/main.cpp -Wall -Wextra -Werror
```
I get an error:
```
/usr/local/include/aegis/fwd.hpp:12:10: fatal error: nlohmann/json_fwd.hpp: No such file or directory
```
I'm investigating on this, looking for some lib I wouldn't have installed on my PC.

**Comment by zeroxs** [comment]
You're missing all the libs being linked, all the include directories, everything.

**Comment by Jm56Z** [comment]
> You're missing all the libs being linked, all the include directories, everything.

You mean I have to install all libs ? I didn't understand it that way, as they are downloaded with the repository.

**Comment by zeroxs** [comment]
No. Right now, you are calling g++ and telling it to only compile the main.cpp. Nothing more. What about the json lib? g++ doesn't know where it is. zlib, openssl, asio, etc. You're missing all the parameters for g++. I would highly recommend using cmake as it does it all for you.

**Comment by Jm56Z** [comment]
Gosh I didn't realise how much I could forget in a few months of not coding C++...
