### ISSUE TITLE
Process aborted by std::terminate()

### ISSUE THREAD

**Issue by yappy** [zeroxs/aegis.cpp#45]
Just a HTTP 401 error causes abnormal process shutdown from the library.
I don't understand the whole design yet, but I assume that it is a little bit too rough.
https://github.com/zeroxs/aegis.cpp/blob/391457cd748fc429003b5127e31ae0acad5a8a4d/include/aegis/impl/core.cpp#L655-L660

Do you have difficulties in restoring the state, for example?
https://github.com/zeroxs/aegis.cpp/commit/44e4c4529705f549f30251a0f69631a246080ab7

**Comment by braindigitalis** [comment]
I've been having these too and been unable to pin them down. If you're sure it's caused by a http 401 i could easily duplicate this issue, and i'll have a look into fixing it :-)

**Comment by braindigitalis** [comment]
can you please have a play with the library and confirm if this is fixed? I reverted a PR which could potentially have caused this by regression, the promise code seems a little hairy and fragile and the fix for that caused other knock-on issues.
